#!/bin/bash
# Lumina Android Build Secrets Setup
# This script adds the required secrets to your GitHub repository

REPO="joynagassi-cyber/luminap"

echo "🔐 Lumina Android Build - Secrets Setup"
echo "========================================="
echo ""
echo "You need to add these secrets to your GitHub repository:"
echo ""
echo "1. ANDROID_KEYSTORE_BASE64"
echo "   - Base64 encoded keystore file (.jks)"
echo "   - Generate one with: keytool -genkeypair -v -keystore release.keystore -alias lumina -keyalg RSA -keysize 2048 -validity 10000"
echo "   - Then: base64 release.keystore"
echo ""
echo "2. ANDROID_KEYSTORE_PASSWORD"
echo "   - Password for the keystore"
echo ""
echo "3. ANDROID_KEYSTORE_KEY_PASSWORD"
echo "   - Password for the key"
echo ""
echo "4. ANDROID_KEYSTORE_ALIAS"
echo "   - Alias for the key (default: lumina)"
echo ""
echo "To add secrets via CLI:"
echo "  gh secret set ANDROID_KEYSTORE_BASE64 -b <base64-content>"
echo "  gh secret set ANDROID_KEYSTORE_PASSWORD -b <password>"
echo "  gh secret set ANDROID_KEYSTORE_KEY_PASSWORD -b <password>"
echo "  gh secret set ANDROID_KEYSTORE_ALIAS -b lumina"
echo ""
echo "Or add them manually at:"
echo "  https://github.com/$REPO/settings/secrets/actions"
echo ""
