// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hhgovvrnalibhgpakswi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_kwbReVxSdHLx_u2IzQvGaA_Eegsf2Sh";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export type Profile = {
  id: string;
  email: string | null;
  first_name: string | null;
  last_name: string | null;
  role: string;
  org_id: string;
};

export type Transaction = {
  id: string;
  org_id: string;
  type: 'INCOME' | 'EXPENSE';
  amount: number;
  description: string;
  date: string;
  status: 'DRAFT' | 'PENDING' | 'APPROVED' | 'REJECTED';
  category_id: string;
  org_unit_id: string | null;
  compensates_for: string | null;
  comment: string | null;
  version: number;
  created_by_id: string | null;
  approved_by_id: string | null;
  created_at: string;
  updated_at: string;
  approved_at: string | null;
  category?: { id: string; key: string; label_fr: string; type: string; org_id: string };
  org_unit?: { id: string; name: string; type: string; org_id: string };
};

export type Category = {
  id: string;
  key: string;
  label_fr: string;
  type: 'INCOME' | 'EXPENSE';
  org_id: string;
};

export type OrgUnit = {
  id: string;
  name: string;
  type: string;
  org_id: string;
};

export type AuditEntry = {
  id: string;
  org_id: string;
  transaction_id: string;
  user_id: string;
  action: string;
  entity_type: string;
  entity_id: string;
  comment: string | null;
  created_at: string;
};
