// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hhgovvrnalibhgpakswi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_kwbReVxSdHLx_u2IzQvGaA_Eegsf2Sh";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
